# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: develop
    ignore:
      - dependency-name: "@fbe/editor"
      - dependency-name: "factorio-wasm"
      - dependency-name: "react-map-interaction"
      - dependency-name: "pako" # v2 does not support required use case
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
