name: Deploy dev

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    environment: blueprints-dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v3
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: yarn
      - run: yarn nx build blueprints
        env:
          CF_WEB_ANALYTICS: 6c563c1e5db141129a5fc95d5c459722
      - name: Authenticate gcloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
      - run: gcloud auth configure-docker --quiet
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: blueprints.github.Dockerfile
          push: true
          tags: eu.gcr.io/factorio-sites/blueprints:dev
      - run: gsutil -h "Cache-Control:public, max-age=31536000" -m rsync -r -d ./dist/apps/blueprints/.next/static gs://factorio-blueprints-assets/dev/_next/static
      - run: gcloud run deploy factorio-blueprints-dev --image=eu.gcr.io/factorio-sites/blueprints:dev --platform managed --region=europe-west4 --remove-env-vars PUBLIC_URL --update-env-vars ASSET_PREFIX=https://factorio-blueprints-assets.storage.googleapis.com/dev,CF_WEB_ANALYTICS=6c563c1e5db141129a5fc95d5c459722
