name: Deploy prd

on:
  push:
    branches:
      - master

jobs:
  deploy:
    environment: blueprints-prd
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: yarn
      - run: yarn db-gen
      - run: yarn nx build blueprints
        env:
          PUBLIC_URL: https://storage.googleapis.com/factorio-blueprints-assets/public
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - run: gcloud auth configure-docker --quiet
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: blueprints.github.Dockerfile
          push: true
          tags: eu.gcr.io/factorio-sites/blueprints
      - run: gsutil -h "Cache-Control:public, max-age=31536000" -m rsync -r -d ./dist/apps/blueprints/.next/static gs://factorio-blueprints-assets/_next/static
      - run: gsutil -h "Cache-Control:public, max-age=31536000" -m rsync -r -d ./dist/apps/blueprints/public gs://factorio-blueprints-assets/public
      - run: gcloud run deploy factorio-blueprints-dev --image=eu.gcr.io/factorio-sites/blueprints --platform managed --region=europe-west4 --update-env-vars PUBLIC_URL=https://storage.googleapis.com/factorio-blueprints-assets/public, ASSET_PREFIX=https://storage.googleapis.com/factorio-blueprints-assets
