name: Validate

on: pull_request

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"
      - run: yarn
      - run: yarn nx run-many --all --target=lint
      - run: yarn nx run-many --all --target=test "--ci"
      - run: yarn nx build blueprints
