name: Nx validate CI

on:
  push:
    branches:
      - dev
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: yarn
      - run: yarn db-gen
      - run: nx lint
      - run: nx test
      - run: nx build blueprints
